version: "3"
services:
  db:
    image: mysql/mysql-server:5.7
    container_name: mysql57
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mos
      TZ: Asia/Shanghai
    ports:
      - 33060:3306
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./sqls:/docker-entrypoint-initdb.d
